# Generated by Django 4.0.1 on 2022-01-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='connected_users',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
