# Generated by Django 4.0.1 on 2022-01-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_alter_room_connected_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='connected_users',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
