# Generated by Django 4.0.1 on 2022-01-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_alter_room_connected_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='prefrence',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
